### ISSUE TITLE
Issue of transparency of contributions in past snapshots

### ISSUE THREAD

**Issue by quertc** [MorpheusAIs/Docs#102] opened 2024-03-14 18:36 UTC
Some contributions (quite a lot of weigth points) in the [snapshot 1 & 2](https://github.com/MorpheusAIs/Docs/blob/main/Contributions/Code%20-%20Proof_Of_Contribution.md) table are anonymous or @username only (without a link to commit or PR). Which removes the transparency of the contributions. Also, some links to code contribution are already outdated and don't work (404). Perhaps this can be re-evaluated and updated somehow to improve transparency.

**Comment by quertc** [comment] 2024-03-14 19:20
There is also a duplicate contribution with First Smart Agent (70 + 70 points).

**Comment by Potentiated** [comment] 2024-03-17 01:34
They have been verified, earlier requests were harder to evaluate everything and as better best practices have been put in place the process is more stringent as to what is been valued and rewarded while been able to keep anonymity of the contributors.

**Comment by DavidAJohnston** [comment] 2024-04-23 20:47
Lot of work on the snap shot clean up.
Should be merged into Github this week so the Smart Contract list of weights and the one on Github match.
Anon contributions are still included. Anons started Morpheus, I see it as a feature not a bug.

**Closed** 2024-04-23 20:46 UTC
